// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6QpzJy3nRMDvfT3_Ynggbb4fI4eCp5M',
    appId: '1:432003490390:web:b35d1c80fd28d0512311f7',
    messagingSenderId: '432003490390',
    projectId: 'authtutorial-99dff',
    authDomain: 'authtutorial-99dff.firebaseapp.com',
    storageBucket: 'authtutorial-99dff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WPHJ5h6bokE6xwfLXzUbwMYIFswlYik',
    appId: '1:432003490390:android:a181185e500ad51d2311f7',
    messagingSenderId: '432003490390',
    projectId: 'authtutorial-99dff',
    storageBucket: 'authtutorial-99dff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1Fv4BpOuOPXaiuH5SenHgOJot3zAC_Y',
    appId: '1:432003490390:ios:3f2168d18ec998c42311f7',
    messagingSenderId: '432003490390',
    projectId: 'authtutorial-99dff',
    storageBucket: 'authtutorial-99dff.appspot.com',
    iosClientId: '432003490390-7nt9fhcifk72ub74hr21bm3puhpe0rnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1Intellij',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1Fv4BpOuOPXaiuH5SenHgOJot3zAC_Y',
    appId: '1:432003490390:ios:3f2168d18ec998c42311f7',
    messagingSenderId: '432003490390',
    projectId: 'authtutorial-99dff',
    storageBucket: 'authtutorial-99dff.appspot.com',
    iosClientId: '432003490390-7nt9fhcifk72ub74hr21bm3puhpe0rnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1Intellij',
  );
}
